# AI-Starter 02: Phân tích dữ liệu với Pandas

In [4]:
# Tạo dữ liệu với Series
import pandas as pd
import numpy as np

s = pd.Series(np.random.randint(100, size=4));
print(s)
print(s.index)
print(s.values)

0    98
1    44
2    87
3    47
dtype: int64
RangeIndex(start=0, stop=4, step=1)
[98 44 87 47]


In [5]:
# Tạo dữ liệu với Series
import pandas as pd
import numpy as np

chi_so = ["Ke toan", "KT", "CNTT", "Co khi"]
gia_tri= [310, 360, 580, 340]
s = pd.Series(gia_tri, index=chi_so);
print(s)
print(s.index)
print(s.values)

Ke toan    310
KT         360
CNTT       580
Co khi     340
dtype: int64
Index(['Ke toan', 'KT', 'CNTT', 'Co khi'], dtype='object')
[310 360 580 340]


In [7]:
# Tạo dữ liệu với Series
import pandas as pd
import numpy as np

chi_so = ["KT", "KT", "CNTT", "Co khi"] # Trùng nhau
gia_tri= [310, 360, 580, 340]
s = pd.Series(gia_tri, index=chi_so);
print(s)
print(s.index)
print(s.values)

KT        310
KT        360
CNTT      580
Co khi    340
dtype: int64
Index(['KT', 'KT', 'CNTT', 'Co khi'], dtype='object')
[310 360 580 340]


In [8]:
# Truy xuất dữ liệu thông qua chỉ số
import pandas as pd
import numpy as np

chi_so = ["KT", "KT", "CNTT", "Co khi"] # Trùng nhau
gia_tri= [310, 360, 580, 340]
s = pd.Series(gia_tri, index=chi_so);
print(s['Co khi'])
print(s['KT'])
print(s.CNTT)

340
KT    310
KT    360
dtype: int64
580


In [16]:
# Phép toán trên series
import pandas as pd
import numpy as np

chi_so = ["Ke toan", "KT", "CNTT", "Co khi"] # Trùng nhau
gia_tri= [310, 360, 580, 340]

# chỉ số giống nhau thì tính gộp, ngược lại NaN
s = pd.Series(gia_tri, index=chi_so);
p = pd.Series([100, 100], ['CNTT', 'PM']);
y = s + p;
print(f'{s} \n---\n{p} \n---\n{y}\n')

Ke toan    310
KT         360
CNTT       580
Co khi     340
dtype: int64 
---
CNTT    100
PM      100
dtype: int64 
---
CNTT       680.0
Co khi       NaN
KT           NaN
Ke toan      NaN
PM           NaN
dtype: float64



## Kết Thúc